const pages = {
  directoryTitle: 'Structs',
  directoryDescription: '',
  pages: [
    {
      title: 'AVL Tree',
      id: 0,
      isMdx: true,
      isFolder: false,
      createdAt: 1727882143,
      modifiedAt: 1727882143,
      route: 'AvlTree.mdx',
      description: 'Data structure for maintaining sorted data',
      tags: ['structs'],
    },
    {
      title: 'Segment Tree',
      id: 1,
      isMdx: true,
      isFolder: false,
      createdAt: 1730045831,
      modifiedAt: 1730045831,
      route: 'fenwickTree.mdx',
      description: 'Data structure for efficient range queries and updates',
      tags: ['structs'],
    },
    {
      title: 'Segment Tree',
      id: 2,
      isMdx: true,
      isFolder: false,
      createdAt: 1726412642,
      modifiedAt: 1727002766,
      route: 'segmentTree.mdx',
      description: 'Data structure for efficient range queries and updates',
      tags: ['structs'],
    },
    {
      title: 'Union Find/ Disjoint Set Union',
      id: 3,
      isMdx: true,
      isFolder: false,
      createdAt: 1727002766,
      modifiedAt: 1727002766,
      route: 'unionFind.mdx',
      description: 'Data structure for checking connectivity between elements',
      tags: ['structs'],
    },
  ],
};
export default pages;
